### ISSUE TITLE
Невероятно долгая загрузка главной страницы модуля

### ISSUE THREAD

**Issue by ToshuK** [maddog670/stream-info#1]
Привет. А почему так долго загружается главная страница модуля? - Я конечно понимаю что подгружаются данные о зрителях/онлайне стримов, но неужели это только они так нагружают процесс загрузки страницы?

Есть еще пару предложений в частности про ускорение загрузки главной страницы, ты принимаешь на доработку? - вроде хорошие идеи.

**Comment by Artyom91** [comment]
Не удобный модуль, я сделал его в виде новостей.

**Comment by maddog670** [comment]
Да принимаю идеи. Если вы даже сделаете реквест, я буду не против.

**Comment by ToshuK** [comment]
maddog670, нет, это функция выключена.

**Comment by maddog670** [comment]
Можно было и сюда прикрепить

**Comment by maddog670** [comment]
1: На данный момент на главной странице модуля (site.ru/stream) выводятся все добавленные трансляции, в то время как при выводе блока онлайн трансляций – выводятся только те трансляции, которые онлайн на данный момент.

Доработка: Почему бы не сделать такое-же для главной страницы? – Это будет очень удобно. (Можно сделать в виде опции для админки, захотел переключил – показываются только онлайн трансляции, не захотел – показываются все трансляции).

И по моему это решит проблему с долгой загрузкой модуля (не уверен) так как я пробовал добавить блок вывода трансляций – такая страница загружалась существенно быстрее.

2: Так-же думаю многим нужен чат трансляции. Например я пользуюсь пока только трансляциями с Twitch.tv – подгрузку чата для трансляций установил себе без проблем. Не знаю как с остальными сервисами, но если возможно – сделать для всех сервисов трансляций добавление чата. (Также это можно реализовать как опцию в админке, захотел – включил, не захотел – выключил. Ну и соответственно можно изменение размеров чата в админку закинуть).

3: Предлагаю добавить в модуль возможность прописывать Title и Description для каждой трансляции. Это существенно повысит SEO продвижение страниц с трансляциями.

4: Было бы не плохо сделать поле «Краткое описание» не обязательным к заполнению. Обожаю минимализм, сделал все максимально просто у себя на сайте, по этому описание ни к чему. Да и вообще не знаю что в него можно писать… Думаю многие о таком задумываются.

5: Возможно ли перетащить с Twitch.tv – еще и тему трансляции? – Её можно было бы использовать например для краткого описания на странице трансляции, ну или вставить над плеером, это уже дело фантазии, но думаю полезная вещь.

**Comment by ToshuK** [comment]
Жаль что не будет SEO правок. На счет дизайна - позже отправлю свой вариант, как окончательно закончу его на своем сайте, глянешь - понравится, можно внести как основной.

**Comment by maddog670** [comment]
> Жаль что не будет SEO правок. На счет дизайна - позже отправлю свой вариант, как окончательно закончу его на своем сайте, глянешь - понравится, можно внести как основной (ну или доп. шаблон).

Если у вас дизайн отличается от дефолтного шаблона, то я думаю не стоит. У всех разные шаблоны и не стоит подстраиваться под каждый.
