### ISSUE TITLE
(Баг) Нельзя удалить трансляции

### ISSUE THREAD

**Issue by ToshuK** [maddog670/stream-info#2]
И снова здравствуйте :) Нашел проблемку, трансляции не удаляются из админки. Ставлю галку, выбираю из выпадающего списка удалить, нажимаю кнопку - и ничего не происходит.

Версия DLE 10.4

**Comment by ToshuK** [comment]
И еще один баг нашел, на главной странице трансляций, появляется по две одинаковые трансляции. То есть каждый раз какая-то из трансляций дублируется.

Версия DLe 10.4

**Comment by maddog670** [comment]
Лично удалялись у меня они. До 10.3 удаление работало хорошо. С дублированием, попробуйте не в index.php подключать, а в /modules/main.php

**Comment by maddog670** [comment]
Поправил удаление

**Comment by ToshuK** [comment]
"С дублированием, попробуйте не в index.php подключать, а в /modules/main.php"
- Да и так-же подключил в main.php, но не все. 

"require_once ENGINE_DIR.'/modules/stream-info-main.php';"
- вставил в index.php

"if( $tpl->result['streams'] != "" && $do != "stream-info") {
    $tpl->set ( '[stream-info]', "" );
    $tpl->set ( '{stream-info}', $tpl->result['streams'] );
    $tpl->set ( '[/stream-info]', "" );
} else {
    $tpl->set_block ( "'\\[stream-info\\](.*?)\\[/stream-info\\]'si", "" );
}"
- вставил в main.php

А че именно изменил для работоспособности удаления, можно как-то глянуть? - Не охота опять модуль переустанавливать...

**Comment by maddog670** [comment]
Правильно. В index.php не надо, а надо только в main.php
как 
```php
if( $tpl->result['streams'] != "" && $do != "stream-info") {
$tpl->set ( '[stream-info]', "" );
$tpl->set ( '{stream-info}', $tpl->result['streams'] );
$tpl->set ( '[/stream-info]', "" );
} else {
$tpl->set_block ( "'\[stream-info\](.*?)\[/stream-info\]'si", "" );
}
```
так и ```php
require_once ENGINE_DIR.'/modules/stream-info-main.php';
```

**Comment by ToshuK** [comment]
Да, перенес второй кусок в main.php - вроде исчезли дубли.

**Comment by ToshuK** [comment]
Выплыл друг баг. Перенос кода в main.php решает проблему дублей, но из-за этого сайт не загружается при перезагрузке. То есть я сижу на какой-то странице сайта, обновляю страницу - и она не загружается, пустая вкладка. Потом нажимаю еще раз обновить - все становится нормально. Вернул код в index.php - проблема исчезла, но опять появились дубли :(

**Comment by maddog670** [comment]
Надо смотреть одним словом.
