### ISSUE TITLE
Что нового?

### ISSUE THREAD

**Issue by ToshuK** [maddog670/stream-info#3]
Вижу некоторые папки изменены 8 дней назад по причине "фикс-апдейт", где-то можно увидеть что нового проделано?

**Comment by maddog670** [comment]
[Фикс](https://github.com/maddog670/stream-info/commit/912ec8a6bbe32fd2c8661e4be07150bb1cb2684f)

**Comment by ToshuK** [comment]
А как там дела с обновлением? - Работаешь?)) Придумал что-то на счет ускорения загрузки главной страницы модуля? - Бо это жуть какая-то, у меня по 1-2 минуты бывает открывается главная с трансляциями :(

**Comment by maddog670** [comment]
Мне сейчас не до этого.
